### ISSUE TITLE
(Javascript) Off By one Error not off by one

### ISSUE THREAD

**Issue by swhalley** [jbrains/trivia#64]
https://github.com/jbrains/trivia/blob/f639bdb30660e4aeb430df438c679e17b6846e74/nodejs/src/game.js#L59-L61

In the javascript, typescript and node versions (possibly more) the one-off error on the player initial states are working as expected. This was an intentional bug

Actual
```
 players.push(playerName);
 places[this.howManyPlayers() - 1] = 0;
 purses[this.howManyPlayers() - 1] = 0;
 inPenaltyBox[this.howManyPlayers() - 1] = false;
```

Expected
```
players.push(playerName);
places[this.howManyPlayers()] = 0;
purses[this.howManyPlayers()] = 0;
inPenaltyBox[this.howManyPlayers()] = false;
```

Additional Notes
JS, unlike some of the original languages in this repo, like Java, have dynamic size arrays. Therefore the same error wont occur when the 6th player is added. Javascript will simply add it to the array. This should be taken into consideration if this ticket moves forward as the same bug may not be reproducible (at least easily) in the JS world. 

Here is a way to have Javascript enforce the array size limits. Not sure if this fits well into the context of the repo
```
let a = new Array(15)
a.fill(undefined)
Object.seal(a)

a.push("Hello") //Errors because the object is sealed.
a[15] = "World" //Silently doesn't add to the array
```

**Comment by jbrains** [comment]
I have chosen to put the bug back as it is and let the bug be more-subtle in JavaScript than in the other languages.

**Comment by jbrains** [comment]
Fixed in https://github.com/jbrains/trivia/commit/668b6bc96201b6910282fd7d293346517b501b34
