### ISSUE TITLE
(Javascript) Correct is spelled correctly

### ISSUE THREAD

**Issue by swhalley** [jbrains/trivia#65]
Javascript versions (including Js, node and typescript) have the word "correct" spelled correctly. this console log should have it spelled "corrent"
https://github.com/jbrains/trivia/blob/f639bdb30660e4aeb430df438c679e17b6846e74/javascript/game.js#L143-L148

They should match the Java version. 

https://github.com/jbrains/trivia/blob/f639bdb30660e4aeb430df438c679e17b6846e74/java/src/main/java/com/adaptionsoft/games/uglytrivia/Game.java#L138-L142

**Comment by jbrains** [comment]
Fixed in https://github.com/jbrains/trivia/commit/1d33da2fa82545828591f3d88b313aafd3ed4c73
